import { NextRequest, NextResponse } from 'next/server'
import * as fs from 'fs'
import * as path from 'path'

/**
 * Serves pre-generated sitemap XML files from /public/sitemaps/.
 * Files are generated by: npx tsx scripts/generate-sitemaps.ts
 */
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string[] }> },
) {
  const { slug } = await params
  const filename = slug.join('/')

  // Safety: only allow simple XML filenames, no path traversal.
  if (!/^[\w-]+\.xml$/.test(filename)) {
    return new NextResponse('Not found', { status: 404 })
  }

  const filePath = path.join(process.cwd(), 'public', 'sitemaps', filename)

  try {
    const content = fs.readFileSync(filePath, 'utf-8')
    return new NextResponse(content, {
      headers: {
        'Content-Type': 'application/xml',
        'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800',
      },
    })
  } catch {
    return new NextResponse('Sitemap not found', { status: 404 })
  }
}
