export const dynamic = "force-dynamic"

import { NextRequest, NextResponse } from 'next/server'
import * as fs from 'fs'
import * as path from 'path'

/**
 * Serves pre-generated sitemap XML files from /public/sitemaps/.
 * Files are generated by: npx tsx scripts/generate-sitemaps.ts
 */
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string[] }> },
) {
  const { slug } = await params
  const filename = slug.join('/')

  // Safety: only allow simple XML filenames, no path traversal.
  if (!/^[\w-]+\.xml$/.test(filename)) {
    return new NextResponse('Not found', {
      status: 404,
      headers: { 'Cache-Control': 'no-store' },
    })
  }

  const filePath = path.join(process.cwd(), 'public', 'sitemaps', filename)

  try {
    const content = fs.readFileSync(filePath, 'utf-8')
    return new NextResponse(content, {
      headers: {
        'Content-Type': 'application/xml',
        // Align closer to index TTL so chunk set / index don't drift for a week.
        'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
      },
    })
  } catch {
    // Missing high-N chunks after a rebuild are expected while Google retries old URLs.
    return new NextResponse('Sitemap not found', {
      status: 404,
      headers: { 'Cache-Control': 'no-store' },
    })
  }
}
